/**
 * @module SET_UPCOMING_LAUNCHES
 * @desc SET_UPCOMING_LAUNCHES constants and its sagas
 */
export const SET_UPCOMING_LAUNCHES = "CONSTANTS/SET_UPCOMING_LAUNCHES";
export const SAGAS_SET_UPCOMING_LAUNCHES = "CONSTANTS/SAGA_SET_UPCOMING_LAUNCHES";

/**
 * @module SET_PAST_LAUNCHES
 * @desc SET_PAST_LAUNCHES constants and its sagas
 */
export const SET_PAST_LAUNCHES = "CONSTANTS/SET_PAST_LAUNCHES";
export const SAGAS_SET_PAST_LAUNCHES = "CONSTANTS/SAGA_SET_PAST_LAUNCHES";